name: Build and deploy ASP.NET Core app to Azure Web App

env:
  AZURE_WEBAPP_NAME: manelpzcleanarchitecture   # Nombre del App Service
  DOTNET_VERSION: '7'                           # Cambia si usas otra versión

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Locate solution and build
        run: |
          SOLUTION=$(find . -name "*.sln")
          echo "Found solution: $SOLUTION"
          dotnet build "$SOLUTION" --configuration Release

      - name: Locate Web API project and publish
        run: |
          PROJECT=$(find . -name "FrameworkDriversAPI.csproj")
          echo "Found project: $PROJECT"
          dotnet publish "$PROJECT" -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./publish
